### ISSUE TITLE
Can't Install In Ubuntu...PLZ help

### ISSUE THREAD

**Issue by Lg-PWNd** [kamwar/simLAB#3]
Hi I've tried to follow the wiki exactly and all required packages listed seemed to download, but i get this when I try to run the program.

`root@simLAB# python ./tests/runner.py
Traceback (most recent call last):
  File "./tests/runner.py", line 14, in <module>
    from sim import sim_router
  File "./tests/../sim/sim_router.py", line 14, in <module>
    import sim_shell
  File "./tests/../sim/sim_shell.py", line 13, in <module>
    import sim_reader
  File "./tests/../sim/sim_reader.py", line 11, in <module>
    from sim_soft import sim_soft_ctrl
  File "./tests/../sim_soft/sim_soft_ctrl.py", line 11, in <module>
    import sim_xml
  File "./tests/../sim_soft/sim_xml.py", line 8, in <module>
    from lxml import etree
ImportError: /usr/local/lib/python2.7/dist-packages/lxml/etree.so: undefined symbol: PyFPE_jbuf `

**Comment by bodziow** [comment]
Hi,

Please uninstall lxml package first:
`sudo pip uninstall lxml`
Then, you can try to reinstall lxml by following the suggestions from:
https://stackoverflow.com/questions/35852646/undefined-symbol-pyfpe-jbuf-error-while-using-lxml-on-ubuntu

**Comment by kamwar** [comment]
Please reopen if it doesn't fix your problem
